config/routes.rb
Rails.application.routes.draw do

  root to: 'welcome#index'
  resources :sessions, only: [:new, :create, :destroy]
  delete 'session' => 'sessions#destroy'

  get '/auth/:provider/callback', to: 'sessions#oauth_create'

  get '/available_items', to: 'items#available_items_show'

  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'

  resources :items, only: [:new, :create, :show, :edit, :update] do
    resources :matches, only: [:index, :show] do
      resources :messages, only: [:new, :create]
    end
  end
  get '/messages/:match_id', to: 'messages#for_match'

  resources :users, only: [:new, :create, :show, :edit, :update]

  resources :swipes, only: [:create]

end

app/models/match.rb
class Match < ActiveRecord::Base
  validates :given_swipe, :received_swipe, presence: true

  belongs_to :given_swipe, class_name: 'Swipe', inverse_of: :given_swipe_matches
  belongs_to :received_swipe, class_name: 'Swipe', inverse_of: :received_swipe_matches

  has_many :messages

  delegate :my_item, to: :given_swipe
  delegate :other_item, to: :given_swipe

  alias item_1 my_item
  alias item_2 other_item

  def other(item)
    item == item_1 ? item_2 : item_1
  end

  def make_swap_if_mutual_swap(item)
    other_item = self.other(item)
    if other_item.swapped
      self.update_attributes(swapped_at: DateTime.now)
    end
  end

  def belongs_to_item?(item)
    item == my_item || item == other_item
  end

end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController

  def show
    @my_item = Item.find_by(id: params[:item_id])
    @match = Match.includes(:messages).find(params[:id])
    @all_messages = @match.messages
    if @my_item && @my_item.user == current_user && @match.belongs_to_item?(@my_item)
      @other_item = @match.other(@my_item)
      @message = Message.new
    else
      render :file => "#{Rails.root}/public/404.html", :status => 404
    end
  end

end

app/views/matches/_match.html.erb
<div class="col-sm-6 col-md-4">
  <div class="thumbnail">
  	<%= image_tag match.other(@item).avatar.url, width: "100", height:"100" %>
    <div class="caption">
      <h3><%= link_to match.other(@item).name, item_match_path(@item, match) %></h3>
      <p><%= match.other(@item).description %></p>
  <div class= "details">
    <i class="fa fa-comment-o"> <%= link_to match.messages.count, item_match_path(@item, match)%> </i>
  </div>
    </div>
  </div>

</div>

app/views/matches/show.html.erb
<h3><%= @my_item.name %> &amp; <%= @other_item.name %></h3>
<div class="row">
  <div class="col-sm-6 col-md-4 item-display" >
    <div class="thumbnail">
      <% if @other_item.avatar %>
      <%= image_tag @other_item.avatar.url(:medium) %>
      <% end %>
      <div class="caption">
        <h3><%= @other_item.name %></h3>
        <p><%= @other_item.description %></p>
      </div>
    </div>
  </div>
  <div class="col-sm-6 col-md-4">
    <div id="chat-panel" class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Conversation</h3>
      </div>
      <div class="chat">
        <div id="chat-sm">
          <% @match.messages.each do |message| %>
          <% if current_user.name == message.user.name %>
          <div class="chat-body clearfix">
            <!-- CAROLINA: MAKE THIS WORK -->
<!--             <div class="thumbnail">
              <%= image_tag message.user.avatar.url(:thumb), class: "img-circle", width: "50" %>
            </div> -->
            <div class="header">
              <strong class="primary-font"><%= message.user.name %></strong>
              <small class="text-muted">
                <span class="glyphicon glyphicon-time"></span>sent at <%= std_format_date(message.created_at) %>
              </small>
            </div>
            <p class="pull-left"><%= message.content %></p>
          </div>
          <% else %>
          <div class="chat-body clearfix">
            <div class="header">
              <strong class="primary-font"><%= message.user.name %></strong>
              <small class=" text-muted">
                <span class="glyphicon glyphicon-time"></span>sent at <%= std_format_date(message.created_at) %>
              </small>
            </div>
            <p class="pull-left"><%= message.content %></p>
          </div>
          <% end %>
          <% end %>
        </div> <!--  End of Chat id -->
        <div class="panel-footer">
          <%= form_for @message, url: item_match_messages_path(@my_item, @match), class: "form-horizontal" do |f| %>

          <div class="input-group">
            <%= f.text_field :content, class: 'form-control input-sm', id:"btn-input" %>
            <span class="input-group-btn">
              <%= f.submit "Send", class:"btn btn-warning btn-sm", id:"btn-chat" %>
            </span>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

    <h4>Item Status</h4>
  <div class="col-sm-6 col-md-4" id="swap-button">
    <% if @my_item.swapped and @other_item.swapped  %>
      <p>Your item is officially swapped!</p>
    <% elsif @my_item.swapped %>
      <p>You have initiated a swap for your item</p>
    <%else %>
    <%= form_for @my_item do |f| %>
      <%= f.hidden_field :swapped %>
      <%= hidden_field_tag "match", @match.id %>
      <%= f.submit "Trade it!", class: "btn btn-lg btn-default" %>
    <% end %>
 <% end %>
  </div>
</div>