config/routes.rb
Rails.application.routes.draw do

  root to: 'welcome#index'
  resources :sessions, only: [:new, :create, :destroy]
  delete 'session' => 'sessions#destroy'

  get '/auth/:provider/callback', to: 'sessions#oauth_create'

  get '/available_items', to: 'items#available_items_show'

  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'

  resources :items, only: [:new, :create, :show, :edit, :update] do
    resources :matches, only: [:index, :show] do
      resources :messages, only: [:new, :create]
    end
  end
  get '/messages/:match_id', to: 'messages#for_match'

  resources :users, only: [:new, :create, :show, :edit, :update]

  resources :swipes, only: [:create]

end

app/models/item.rb
class Item < ActiveRecord::Base
  validates :name, presence: true, length: {minimum: 2, maximum: 50}
  validates :description, presence: true, length: {maximum: 1000}
  validates :user_id, presence: true

  belongs_to  :user
  has_many    :given_swipes, foreign_key: :my_item_id, class_name: "Swipe"
  has_many    :received_swipes, foreign_key: :other_item_id, class_name: "Swipe"

  #Necessary only for other associations
  has_many    :given_swipe_matches, through: :given_swipes
  has_many    :received_swipe_matches, through: :received_swipes

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "https://placehold.it/300.png/09f/fff"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  def all_matches
     ids = given_swipe_matches.pluck(:id) + received_swipe_matches.pluck(:id)
     Match.where(id: ids)
  end

  def self.available(user)
    where_clause = " user_id != ? and id not in " +
     " (       select s.other_item_id from swipes s join items i on i.id = s.my_item_id " +
     "  where i.user_id = ? ) "
    availables = where(where_clause, user.id, user.id)
    availables.reject{|item| item.swapped }
  end

  def avatar_url
    avatar.url(:medium)
  end

  def add_default_image
    self.avatar_file_name = 'https://placehold.it/300.png/09f/fff'
  end

  def swapped_matches
    self.all_matches.detect { |match| match.swapped_at != nil }
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  #before_action for ownership

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to item_path(@item)
    else
      flash[:notice] = "We could not save your treasure. Please try again."
      redirect_to new_item_path
    end
  end

  def show
    @item = Item.find_by(id: params[:id])
    if @item && @item.user == current_user
      @matches = @item.all_matches
      @has_matches = @matches.any?
      @swapped_match = @item.swapped_matches
      @other_swapped_item = @swapped_match.other(@item).name if @swapped_match
    else
      render :file => "#{Rails.root}/public/404.html", :status => 404
    end
  end

  def available_items_show
    @swipe = Swipe.new
    available_items = Item.available(current_user)
    @item = available_items.shuffle.sample
    if request.xhr?
      if available_items.any?
        render json: @item, methods: [:avatar_url]
      else
        render json:{message: "No More Items"}
      end
    else
      if available_items.any?
        @item
      else
        render "items/_out_of_swipes"
      end
    end
  end

  def edit
    @item = Item.find(params[:id])
    if @item.user != current_user
      render :file => "#{Rails.root}/public/404.html", :status => 404
    end
  end

  def update
    @item = Item.find_by(id: params[:id])

    if params[:item][:swapped]
      if @item.swapped == false
        @match = Match.find(params[:match])
        @item.update_attributes(swapped: true)
        @match.make_swap_if_mutual_swap(@item)
        if @match.swapped_at != nil
          flash[:notice] = "Both treasures have confirmed your swap!"
        else
          flash[:notice] = 'When the other item in your match confirms, your items will be unlisted.'
        end
      end
      redirect_to item_match_path(@item, @match)

    else
      if @item.update_attributes(item_params)
        flash[:notice] = "Item updated"
        redirect_to @item
      else
        flash[:alert] = "Did not update"
        render :edit
      end
    end
  end


  private

  def item_params
    params.require(:item).permit(:name, :description, :avatar).merge(user: current_user)
  end
end

app/views/items/_form.html.erb
<div class="left">
<%= form_for(@item, html: {class: 'form-horizontal', multipart: true}) do |f| %>

  <div class="form-group">
    <%= f.label :name, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :description, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
      <label name="zipcode" class='col-sm-2 control-label'>Zipcode: </label>
    <div class="col-sm-10">
      <%= text_field_tag "zipcode", nil, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :avatar, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.file_field :avatar, id: 'exampleInputFile' %>
    </div>
  </div>
  <div class="actions form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class:"btn btn-default"%>
    </div>
  </div>

<% end %>
</div>

app/views/items/_item.erb
<% if item.avatar %>
  <%= image_tag item.avatar.url(:medium) %>
<% end %>

<h3><%= item.name %></h3>
<p><%= item.description %></p>
<%= link_to "Edit my item", edit_item_path if item.user == current_user%>

app/views/items/_matches_list.html.erb
<h3>Matches:</h3>

<div class="row">
  <%= render @matches %>

</div>

app/views/items/_out_of_swipes.html.erb
<p>You're out of swipes. Check back soon!</p>

app/views/items/_swipe_item.html.erb
<div id="item-container">
  <%= image_tag item.avatar.url(:medium) %>
  <h3><%= item.name %></h3>
  <p><%= item.description %></p>
</div>

app/views/items/available_items_show.html.erb
<div class='available-items-container'>
  <% if @item %>
    <%= render partial: "swipe_item", locals: {item: @item} %>

    <%= form_for @swipe, html: {class: 'swipe-action', id: 'swipe-left'} do |f| %>
      <%= f.hidden_field :direction, value: "L" %>
      <%= f.hidden_field :other_item_id, value: @item.id %>
      <%= f.submit "swipe left", class: "sr-only" %>
      <%= f.button class: 'btn btn-default btn-lg', name:"commit" do %>
        <i class="fa fa-close"></i>
      <% end %>
    <% end %>

    <%= form_for @swipe, html: {class: 'swipe-action', id: 'swipe-right'} do |f| %>
      <%= f.hidden_field :direction, value: "R" %>
      <%= f.hidden_field :other_item_id, value: @item.id %>
      <%= f.submit "swipe right", class: "sr-only" %>
      <%= f.button class: 'btn btn-default btn-lg', name:"commit" do %>
        <i class="fa fa-check"></i>
      <% end %>
    <% end %>

  <% end %>
</div>

<!-- MODAL CODE BELOW -->
<div class="modal fade center" id="myModal" tabindex="-1" role="dialog" aria-labelledby="gridSystemModalLabel">
  <div class="vertical-alignment-helper">
    <div class="modal-dialog vertical-align-center">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
              <h4 class="modal-title" id="myModalLabel"></h4>

          </div>

          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/items/edit.html.erb
<h2>Edit Item</h2>
<%= render 'form', locals: {item: @item} %>

  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h4><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h4>
     <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

app/views/items/new.html.erb
<h2>List your item</h2>
<%= render 'form' %>

app/views/items/show.html.erb
<div>
    <%= render @item %>

    <% if @other_swapped_item %>
      <p>You've traded with <%= @other_swapped_item %>.</p>
      <% end %>

    <% if @has_matches %>
      <%= render 'matches_list' %>
    <% end %>
</div>