config/routes.rb
Rails.application.routes.draw do

  root to: 'welcome#index'
  resources :sessions, only: [:new, :create, :destroy]
  delete 'session' => 'sessions#destroy'

  get '/auth/:provider/callback', to: 'sessions#oauth_create'

  get '/available_items', to: 'items#available_items_show'

  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'

  resources :items, only: [:new, :create, :show, :edit, :update] do
    resources :matches, only: [:index, :show] do
      resources :messages, only: [:new, :create]
    end
  end
  get '/messages/:match_id', to: 'messages#for_match'

  resources :users, only: [:new, :create, :show, :edit, :update]

  resources :swipes, only: [:create]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

  <title>Treasure</title>
  <!-- Treasure Font -->
  <link href='https://fonts.googleapis.com/css?family=Patua+One' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Roboto:400,300,500' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">

  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all' %>

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
</head>
<body>
    <div class="container">
      <!-- Static navbar -->
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <%= link_to 'treasure', root_path, class: "navbar-brand black"%>
          <% if current_user and current_user.items.first %>
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
            <li><a class="username"></a></li>
            <li><%= link_to current_user.name, current_user %></li>
            <li><%= link_to 'My Treasure', item_path(current_user.items.first) %> </li>
            <li><%= link_to 'Logout', session_path(current_user), method: :delete %> </li>
            </ul>
            <% end %>
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>
    </header>

    <div class="flash">
      <% if flash[:notice] %>
        <p class="notice"><%= flash[:notice] %></p>
      <% end %>

      <% if flash[:alert] %>
        <p class="alert"><%= flash[:alert] %></p>
      <% end %>
    </div>

    <main id="main-body">
      <%= yield %>
    </div>

    </div> <!-- /container -->


  </body>
</html>